import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Contents from "@/components/Contents";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="flex h-screen">
          <Sidebar />
          <Contents>{children}</Contents>
        </main>
      </body>
    </html>
  );
}
